package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val Primary = Color(0xFF000000)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF131B2E)
val OnPrimaryContainer = Color(0xFF7C839B)
val Secondary = Color(0xFF006C4A)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF82F5C1)
val OnSecondaryContainer = Color(0xFF00714E)
val Tertiary = Color(0xFF000000)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF07006C)
val OnTertiaryContainer = Color(0xFF7073FF)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
val Background = Color(0xFFF7F9FB)
val OnBackground = Color(0xFF191C1E)
val Surface = Color(0xFFF7F9FB)
val OnSurface = Color(0xFF191C1E)
val SurfaceVariant = Color(0xFFE0E3E5)
val OnSurfaceVariant = Color(0xFF45464D)
val Outline = Color(0xFF76777D)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF2F4F6)
val SurfaceContainer = Color(0xFFECEEF0)
val SurfaceContainerHigh = Color(0xFFE6E8EA)
val SurfaceContainerHighest = Color(0xFFE0E3E5)
val SurfaceTint = Color(0xFF565E74)
val OutlineVariant = Color(0xFFC6C6CD)
